<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['title' => 'Казахстан', 'code' => 'KZ'],
            ['title' => 'Россия', 'code' => 'RU'],
            ['title' => 'Узбекистан', 'code' => 'UZ'],
            ['title' => 'Кыргызстан', 'code' => 'KG'],
            ['title' => 'Беларусь', 'code' => 'BY'],
            ['title' => 'Азербайджан', 'code' => 'AZ'],
            ['title' => 'Армения', 'code' => 'AM'],
            ['title' => 'Грузия', 'code' => 'GE'],
            ['title' => 'Молдова', 'code' => 'MD'],
            ['title' => 'Таджикистан', 'code' => 'TJ'],
            ['title' => 'Туркменистан', 'code' => 'TM'],
            ['title' => 'Украина', 'code' => 'UA'],
            ['title' => 'Австралия', 'code' => 'AU'],
            ['title' => 'Австрия', 'code' => 'AT'],
            ['title' => 'Албания', 'code' => 'AL'],
            ['title' => 'Алжир', 'code' => 'DZ'],
            ['title' => 'Андорра', 'code' => 'AD'],
            ['title' => 'Ангола', 'code' => 'AO'],
            ['title' => 'Аргентина', 'code' => 'AR'],
            ['title' => 'Афганистан', 'code' => 'AF'],
            ['title' => 'Багамы', 'code' => 'BS'],
            ['title' => 'Бангладеш', 'code' => 'BD'],
            ['title' => 'Барбадос', 'code' => 'BB'],
            ['title' => 'Бахрейн', 'code' => 'BH'],
            ['title' => 'Бельгия', 'code' => 'BE'],
            ['title' => 'Белиз', 'code' => 'BZ'],
            ['title' => 'Бенин', 'code' => 'BJ'],
            ['title' => 'Болгария', 'code' => 'BG'],
            ['title' => 'Боливия', 'code' => 'BO'],
            ['title' => 'Босния и Герцеговина', 'code' => 'BA'],
            ['title' => 'Бразилия', 'code' => 'BR'],
            ['title' => 'Бруней', 'code' => 'BN'],
            ['title' => 'Буркина-Фасо', 'code' => 'BF'],
            ['title' => 'Бурунди', 'code' => 'BI'],
            ['title' => 'Бутан', 'code' => 'BT'],
            ['title' => 'Вануату', 'code' => 'VU'],
            ['title' => 'Ватикан', 'code' => 'VA'],
            ['title' => 'Великобритания', 'code' => 'GB'],
            ['title' => 'Венгрия', 'code' => 'HU'],
            ['title' => 'Венесуэла', 'code' => 'VE'],
            ['title' => 'Вьетнам', 'code' => 'VN'],
            ['title' => 'Германия', 'code' => 'DE'],
            ['title' => 'Гондурас', 'code' => 'HN'],
            ['title' => 'Греция', 'code' => 'GR'],
            ['title' => 'Дания', 'code' => 'DK'],
            ['title' => 'Египет', 'code' => 'EG'],
            ['title' => 'Израиль', 'code' => 'IL'],
            ['title' => 'Индия', 'code' => 'IN'],
            ['title' => 'Индонезия', 'code' => 'ID'],
            ['title' => 'Иордания', 'code' => 'JO'],
            ['title' => 'Ирак', 'code' => 'IQ'],
            ['title' => 'Иран', 'code' => 'IR'],
            ['title' => 'Ирландия', 'code' => 'IE'],
            ['title' => 'Исландия', 'code' => 'IS'],
            ['title' => 'Испания', 'code' => 'ES'],
            ['title' => 'Италия', 'code' => 'IT'],
            ['title' => 'Йемен', 'code' => 'YE'],
            ['title' => 'Камбоджа', 'code' => 'KH'],
            ['title' => 'Камерун', 'code' => 'CM'],
            ['title' => 'Канада', 'code' => 'CA'],
            ['title' => 'Катар', 'code' => 'QA'],
            ['title' => 'Кипр', 'code' => 'CY'],
            ['title' => 'Китай', 'code' => 'CN'],
            ['title' => 'Колумбия', 'code' => 'CO'],
            ['title' => 'Корея (Южная)', 'code' => 'KR'],
            ['title' => 'Куба', 'code' => 'CU'],
            ['title' => 'Кувейт', 'code' => 'KW'],
            ['title' => 'Латвия', 'code' => 'LV'],
            ['title' => 'Ливан', 'code' => 'LB'],
            ['title' => 'Литва', 'code' => 'LT'],
            ['title' => 'Лихтенштейн', 'code' => 'LI'],
            ['title' => 'Люксембург', 'code' => 'LU'],
            ['title' => 'Малайзия', 'code' => 'MY'],
            ['title' => 'Мальта', 'code' => 'MT'],
            ['title' => 'Мексика', 'code' => 'MX'],
            ['title' => 'Монако', 'code' => 'MC'],
            ['title' => 'Монголия', 'code' => 'MN'],
            ['title' => 'Мьянма', 'code' => 'MM'],
            ['title' => 'Непал', 'code' => 'NP'],
            ['title' => 'Нидерланды', 'code' => 'NL'],
            ['title' => 'Новая Зеландия', 'code' => 'NZ'],
            ['title' => 'Норвегия', 'code' => 'NO'],
            ['title' => 'ОАЭ', 'code' => 'AE'],
            ['title' => 'Оман', 'code' => 'OM'],
            ['title' => 'Пакистан', 'code' => 'PK'],
            ['title' => 'Панама', 'code' => 'PA'],
            ['title' => 'Перу', 'code' => 'PE'],
            ['title' => 'Польша', 'code' => 'PL'],
            ['title' => 'Португалия', 'code' => 'PT'],
            ['title' => 'Румыния', 'code' => 'RO'],
            ['title' => 'Саудовская Аравия', 'code' => 'SA'],
            ['title' => 'Сербия', 'code' => 'RS'],
            ['title' => 'Сингапур', 'code' => 'SG'],
            ['title' => 'Сирия', 'code' => 'SY'],
            ['title' => 'Словакия', 'code' => 'SK'],
            ['title' => 'Словения', 'code' => 'SI'],
            ['title' => 'США', 'code' => 'US'],
            ['title' => 'Таиланд', 'code' => 'TH'],
            ['title' => 'Тайвань', 'code' => 'TW'],
            ['title' => 'Тунис', 'code' => 'TN'],
            ['title' => 'Турция', 'code' => 'TR'],
            ['title' => 'Филиппины', 'code' => 'PH'],
            ['title' => 'Финляндия', 'code' => 'FI'],
            ['title' => 'Франция', 'code' => 'FR'],
            ['title' => 'Хорватия', 'code' => 'HR'],
            ['title' => 'Черногория', 'code' => 'ME'],
            ['title' => 'Чехия', 'code' => 'CZ'],
            ['title' => 'Швейцария', 'code' => 'CH'],
            ['title' => 'Швеция', 'code' => 'SE'],
            ['title' => 'Шри-Ланка', 'code' => 'LK'],
            ['title' => 'Эстония', 'code' => 'EE'],
            ['title' => 'ЮАР', 'code' => 'ZA'],
            ['title' => 'Япония', 'code' => 'JP'],
        ];

        foreach ($countries as $country) {
            Country::firstOrCreate(['title' => $country['title']], $country);
        }
    }
}